# Generated by Django 4.1.1 on 2022-09-25 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.IntegerField(choices=[(1, 'Income'), (2, 'Expense'), (3, 'Transfer')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('kind', models.IntegerField(choices=[(1, 'Income'), (2, 'Expense'), (3, 'Transfer')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account'
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        default='Unknown',
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to='history.category',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
